// <auto-generated />
using System;
using FinGuard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516120551_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("FinGuard.API.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CariAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaturaTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KesimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VadeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("FinGuard.API.Models.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonGuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamBakiye")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hesaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
