// <auto-generated />
using System;
using FinGuard.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinGuard.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516164518_AddAuthAndUsers")]
    partial class AddAuthAndUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("FinGuard.API.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CariAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FaturaTipi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KesimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VadeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("FinGuard.API.Models.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonGuncellenmeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ToplamBakiye")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("FinGuard.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinGuard.API.Models.Fatura", b =>
                {
                    b.HasOne("FinGuard.API.Models.User", "User")
                        .WithMany("Faturalar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinGuard.API.Models.Hesap", b =>
                {
                    b.HasOne("FinGuard.API.Models.User", "User")
                        .WithMany("Hesaplar")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinGuard.API.Models.User", b =>
                {
                    b.Navigation("Faturalar");

                    b.Navigation("Hesaplar");
                });
#pragma warning restore 612, 618
        }
    }
}
